###get api 
GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ4NjA1ODksImV4cCI6MTcyNjQxODE4OSwiYXVkIjoiNjUwNTU3YjdkYzQ0Y2YxM2VhODQ2MzUzIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.aOMjWrSLDRr0KIl49vG8choGCgu9Wn6yiR4iM278N0U

### login Route
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "saurabh"
}

### Register Route
POST http://localhost:3000/users/register
Content-Type: application/json

{   "name":"admin",
    "email": "admin@gmail.com",
    "password": "saurabh",
    "confirmPassword": "saurabh",
    "photo": "https://api.slingacademy.com/public/sample-photos/1.jpeg"
}

### Refresh Route
POST http://localhost:3000/users/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQzMzE1MDksImV4cCI6MTcyNTg4OTEwOSwiYXVkIjoiNjRmYWM0ZDE0NTZjMWU4NjU3YWVhZjQxIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.CKqZAHQogbQV9yHpSDsVRTmt41MO7SYE8G6ofTyNyvI"
}


### Logout Route
DELETE http://localhost:3000/users/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTM3NTk5MjIsImV4cCI6MTcyNTMxNzUyMiwiYXVkIjoiNjRmNDY0YTJkZmE3YjkxYzZiNmQyN2UwIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.xQx3gWwTnaNcnLs7KtzzKhQJYV8vT43O7hmCq3dl5qU"
}

###  CREATE PRODUCT
POST http://localhost:3000/product
Content-Type: application/json

 {
    "name": "sikha Gupta",
    "price": "45000",
    "description": "good",
    "category":"mobile" ,
    "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg"

  }

###  PRODUCT LIST
GET http://localhost:3000/product
Content-Type: : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQxNjk1MjgsImV4cCI6MTY5NDE4MDMyOCwiYXVkIjoiNjRmYWM0ZDE0NTZjMWU4NjU3YWVhZjQxIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.nx2OVm2_tXhrwKnTMq7yHQk_8SafUmZvu8HhYcNzKJo

### FIND PRODUCT BY ID
GET  http://localhost:3000/product/64fc14d349c7f6472a35e8b1
Content-Type: application/json


### DELETE PRODUCT BY ID
DELETE http://localhost:3000/product/64fc14d349c7f6472a35e8b1
Content-Type: application/json


### UPDATE PRODUCT
PATCH http://localhost:3000/product/64fb173d8abb9ad6e020a661
Content-Type: application/json

{
  "name": "Iphone",
  "price": "450000"
}


### CREATE CUSTOMER
POST http://localhost:3000/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ4NDg5NTUsImV4cCI6MTcyNjQwNjU1NSwiYXVkIjoiNjUwNTU3YjdkYzQ0Y2YxM2VhODQ2MzUzIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.CfQUmnvVSSQndKQWTyXIdy6XTTmY_FkGBZ5QVYfROG0
Content-Type: application/json

  {
    "name": "Saurabh Kumar",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "address": "Multi-layered client-server neural-net"
    }
}


### LIST CUSTOMER
GET http://localhost:3000/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQzMzIzOTIsImV4cCI6MTcyNTg4OTk5MiwiYXVkIjoiNjRmYWM0ZDE0NTZjMWU4NjU3YWVhZjQxIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.alKhXbin8VAr2D4lHX0OzqdKqejdP5XlbrKX8FSRLbE


### FIND CUSTOMER BY ID
GET http://localhost:3000/customers/64fc4081b25539672165fdcf
Content-Type: application/json


### DELETE CUSTOMER
DELETE  http://localhost:3000/customers/64fc40d96ae8034a63a50a06
Content-Type: application/json

### UPDATE CUSTOMER
PATCH http://localhost:3000/customers/64fc4081b25539672165fdcf
Content-Type: application/json

{
  "name": "saurabh kumar soni",
  "email": "saurabh@gmail.com"
}

### add moview
POST http://localhost:3000/movie
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTUxNDY2MDIsImV4cCI6MTY5NTE0NjYyMiwiYXVkIjoiNjUwOWRmOTBmNTcxOGIyZDcxOWNkNWQ4IiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.5VKG7qwWvH8_sIz0iULjtexv32Xma-oWsRLlazo3aEA
Content-Type: application/json

{
      "name":"sample movie 3",
      "description":"An iconic Bollywood action film",
      "runtime":304,
      "director": "Saurabh Soni",
      "actors": "Dharmendra, Amitabh Bachchan, Hema Malini, Jaya Bhaduri",
      "posterUrl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYzdiZTU3NGUtZmNkYi00Y2EwLWEwYjAtNjk4ZTBlOTVhYTU2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
      "releaseYear":2023,
      "ratings": 5,
      "totalRatings":5123,
      "releaseDate":"2023-10-21",
      "genres":[
         "Action",
         "Adventure",
         "Drama"
      ],
      "price":700
   }

### get movie list
GET  http://localhost:3000/movie
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTUyMDU3NzYsImV4cCI6MTcyNjc2MzM3NiwiYXVkIjoiNjUwYWJlMGRjMmRmNDcyMDE0Y2NhYjMyIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.KLw2_Dd5q3oqiaa3cje1mtq4l3pTnTNqAfsJNjCb4Yc
Content-Type: application/json


### filter movie list

GET  http://localhost:3000/movie/?runtime[gte]=150&ratings[gte]=4.6&limit=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ4NDg5NTUsImV4cCI6MTcyNjQwNjU1NSwiYXVkIjoiNjUwNTU3YjdkYzQ0Y2YxM2VhODQ2MzUzIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.CfQUmnvVSSQndKQWTyXIdy6XTTmY_FkGBZ5QVYfROG0
Content-Type: application/json


### sort movie list
GET  http://localhost:3000/movie/?sort=releaseYear,ratings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ4NDg5NTUsImV4cCI6MTcyNjQwNjU1NSwiYXVkIjoiNjUwNTU3YjdkYzQ0Y2YxM2VhODQ2MzUzIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.CfQUmnvVSSQndKQWTyXIdy6XTTmY_FkGBZ5QVYfROG0
Content-Type: application/json


###limiting the fields
GET  http://localhost:3000/movie/?fields=name,runtime,releaseYear,ratings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ4NDg5NTUsImV4cCI6MTcyNjQwNjU1NSwiYXVkIjoiNjUwNTU3YjdkYzQ0Y2YxM2VhODQ2MzUzIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.CfQUmnvVSSQndKQWTyXIdy6XTTmY_FkGBZ5QVYfROG0
Content-Type: application/json


### pagination and limit number
GET  http://localhost:3000/movie/?page=4&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ4NDg5NTUsImV4cCI6MTcyNjQwNjU1NSwiYXVkIjoiNjUwNTU3YjdkYzQ0Y2YxM2VhODQ2MzUzIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.CfQUmnvVSSQndKQWTyXIdy6XTTmY_FkGBZ5QVYfROG0
Content-Type: application/json

### use all in one
GET  http://localhost:3000/movie/?limit=5&sort=-runtime
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ4NDg5NTUsImV4cCI6MTcyNjQwNjU1NSwiYXVkIjoiNjUwNTU3YjdkYzQ0Y2YxM2VhODQ2MzUzIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.CfQUmnvVSSQndKQWTyXIdy6XTTmY_FkGBZ5QVYfROG0
Content-Type: application/json

#### highest rated
GET  http://localhost:3000/movie/highest-rated
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ4NDg5NTUsImV4cCI6MTcyNjQwNjU1NSwiYXVkIjoiNjUwNTU3YjdkYzQ0Y2YxM2VhODQ2MzUzIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.CfQUmnvVSSQndKQWTyXIdy6XTTmY_FkGBZ5QVYfROG0
Content-Type: application/json

#### DELETE MOVIE IF HAVING ADMIN PERMISSION
DELETE   http://localhost:3000/movie/65099bccc5d64b931b34323f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJpYXQiOjE2OTUzMTg5NDcsImV4cCI6MTY5NTMyMjU0NywiYXVkIjoiNjUwYzgxZjQxYTc2YzczZjRmOWU1ODRmIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.yHjzGEbEqohtZ1wS4MbB3bzcHdmgB4O4ot4P4_QdDcM
Content-Type: application/json

### find by id
GET http://localhost:3000/movie/65099a72d7e74abaa1ecab15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTQ4NDg5NTUsImV4cCI6MTcyNjQwNjU1NSwiYXVkIjoiNjUwNTU3YjdkYzQ0Y2YxM2VhODQ2MzUzIiwiaXNzIjoiZ29vZ2xlLmNvbSJ9.CfQUmnvVSSQndKQWTyXIdy6XTTmY_FkGBZ5QVYfROG0
Content-Type: application/json
